# Generated by Django 3.0.8 on 2020-07-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datas',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datas',
            name='booth_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datas',
            name='house_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datas',
            name='id_card_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
