# Generated by Django 3.0.8 on 2020-08-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linapp', '0002_auto_20200731_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='house_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datas',
            name='id_card_no',
            field=models.CharField(max_length=100),
        ),
    ]
